language: node_js

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - 8

install:
  - yarn

script:
  - SPACE_ID=9yxuzkcxr8zo ACCESS_TOKEN=qTQx1rAnc3eEoAWcGnQuBA8VMrjzd_ljuBSDtgZV6xQ yarn build
  - yarn lint

branches:
  only:
    - master
    - '/^greenkeeper/.*$/'
